# Generated by Django 4.2.4 on 2023-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0002_noticiajuntavecinos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='id_sede',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
