# Generated by Django 4.2.4 on 2023-09-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0003_usuariopersonalizado_id_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='id_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_id_sede', to='vecindad.juntadevecinos', to_field='id_sede'),
        ),
    ]
