# Generated by Django 4.2.4 on 2023-09-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0004_alter_usuariopersonalizado_id_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='id_sede',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
