# Generated by Django 4.2.4 on 2023-10-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0006_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='solicitud_espacios',
            field=models.CharField(blank=True, choices=[('cancha', 'Cancha'), ('sala', 'Sala'), ('plaza', 'Plaza'), ('otro', 'Otro')], max_length=10, verbose_name='Tipo de Espacio Solicitado'),
        ),
    ]
