# Generated by Django 4.2.4 on 2023-10-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0008_mensaje_fecha_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_solicitud',
            new_name='solicitud_fecha_hora',
        ),
    ]
