# Generated by Django 4.2.4 on 2023-10-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0011_mensaje_asunto_delete_mensajemodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='contenido_presidente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
