# Generated by Django 4.2.4 on 2023-10-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0012_mensaje_contenido_presidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rut',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
