# Generated by Django 4.2.4 on 2023-10-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0013_usuariopersonalizado_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='rut',
        ),
    ]
