# Generated by Django 4.2.4 on 2023-10-10 03:50

from django.db import migrations, models
import vecindad.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vecindad', '0015_usuariopersonalizado_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rut',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[vecindad.validators.validate_rut]),
        ),
    ]
